services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  json.encoder:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder

  # Нормалайзер объектов.
  object.normalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer

  # Сериализатор.
  serialize:
    class: Symfony\Component\Serializer\Serializer
    arguments:
      $normalizers:
        - '@object.normalizer'
      $encoders:
        - '@json.encoder'

  Symfony\Component\Serializer\Serializer: '@serialize'
  Symfony\Component\Serializer\SerializerInterface: '@serialize'

  serializer: '@serialize'
